import { type StudyOutputType } from './study-types';

export function tryParseStudyJson(text: string) {
  const cleaned = text.replace(/```json\n?|\n?```/g, '').trim();
  try {
    return JSON.parse(cleaned);
  } catch {
    return null;
  }
}

export function formatStudyAsText(
  type: StudyOutputType,
  result: string,
  sourceFileName: string
) {
  const data = type !== 'notes' ? tryParseStudyJson(result) : null;
  const header = `StudyAI — ${type}\nSource: ${sourceFileName}\n${'='.repeat(48)}\n\n`;

  if (type === 'notes' || !data) {
    return header + result;
  }

  if (type === 'quiz' && data.questions) {
    let text = header + `${data.title}\n\n`;
    data.questions.forEach(
      (
        q: {
          question: string;
          options: string[];
          correctIndex: number;
          explanation: string;
        },
        i: number
      ) => {
        text += `${i + 1}. ${q.question}\n`;
        q.options.forEach((opt: string, j: number) => {
          const mark = j === q.correctIndex ? ' ✓' : '';
          text += `   ${String.fromCharCode(65 + j)}. ${opt}${mark}\n`;
        });
        text += `   Explanation: ${q.explanation}\n\n`;
      }
    );
    return text;
  }

  if (type === 'slides' && data.slides) {
    let text = header + `${data.title}\n\n`;
    data.slides.forEach(
      (
        slide: { title: string; bullets: string[]; speakerNotes?: string },
        i: number
      ) => {
        text += `Slide ${i + 1}: ${slide.title}\n`;
        slide.bullets.forEach((b: string) => {
          text += `  • ${b}\n`;
        });
        if (slide.speakerNotes) text += `  Notes: ${slide.speakerNotes}\n`;
        text += '\n';
      }
    );
    return text;
  }

  if (type === 'infographic' && data.sections) {
    let text = header + `${data.title}\n${data.tagline || ''}\n\n`;
    if (data.keyStats) {
      text += 'Key stats:\n';
      data.keyStats.forEach((s: string) => {
        text += `  • ${s}\n`;
      });
      text += '\n';
    }
    data.sections.forEach(
      (section: { heading: string; points: string[]; stat?: string }) => {
        text += `${section.heading}\n`;
        if (section.stat) text += `  ${section.stat}\n`;
        section.points.forEach((p: string) => {
          text += `  • ${p}\n`;
        });
        text += '\n';
      }
    );
    return text;
  }

  if (type === 'flashcards' && data.cards) {
    let text = header + `${data.title}\n\n`;
    data.cards.forEach((card: { question: string; answer: string }, i: number) => {
      text += `Card ${i + 1}\nQ: ${card.question}\nA: ${card.answer}\n\n`;
    });
    return text;
  }

  return header + result;
}

export function getExportBaseName(fileName: string, type: StudyOutputType) {
  const base = fileName.replace(/\.[^.]+$/, '') || 'study';
  return `${base}-${type}`.replace(/[^a-z0-9-_]+/gi, '-').toLowerCase();
}

export function downloadTextFile(content: string, filename: string) {
  const blob = new Blob([content], { type: 'text/plain;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  link.click();
  URL.revokeObjectURL(url);
}

export async function downloadPdf(
  content: string,
  filename: string,
  title: string
) {
  const { jsPDF } = await import('jspdf');
  const doc = new jsPDF({ unit: 'mm', format: 'a4' });
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 14;
  const maxWidth = pageWidth - margin * 2;
  let y = 20;

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(16);
  doc.text(title, margin, y);
  y += 10;

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(11);
  const lines = doc.splitTextToSize(content, maxWidth);

  for (const line of lines) {
    if (y > doc.internal.pageSize.getHeight() - 20) {
      doc.addPage();
      y = 20;
    }
    doc.text(line, margin, y);
    y += 6;
  }

  doc.save(filename);
}

export async function downloadPptx(
  slidesData: {
    title: string;
    slides: Array<{ title: string; bullets: string[]; speakerNotes?: string }>;
  },
  filename: string
) {
  const PptxGenJS = (await import('pptxgenjs')).default;
  const pptx = new PptxGenJS();
  pptx.author = 'StudyAI';
  pptx.title = slidesData.title;

  const titleSlide = pptx.addSlide();
  titleSlide.background = { color: '1A1A3F' };
  titleSlide.addText(slidesData.title, {
    x: 0.5,
    y: 2.2,
    w: 9,
    h: 1.5,
    fontSize: 32,
    bold: true,
    color: 'FFFFFF',
    align: 'center',
  });
  titleSlide.addText('Generated by StudyAI', {
    x: 0.5,
    y: 4,
    w: 9,
    fontSize: 14,
    color: 'A78BFA',
    align: 'center',
  });

  slidesData.slides.forEach((slide) => {
    const s = pptx.addSlide();
    s.background = { color: '0F0F23' };
    s.addText(slide.title, {
      x: 0.5,
      y: 0.4,
      w: 9,
      h: 0.8,
      fontSize: 24,
      bold: true,
      color: 'FFFFFF',
    });
    s.addText(slide.bullets.map((b) => `• ${b}`).join('\n'), {
      x: 0.5,
      y: 1.4,
      w: 9,
      h: 4,
      fontSize: 16,
      color: 'E2E8F0',
      valign: 'top',
    });
  });

  await pptx.writeFile({ fileName: filename });
}
